package dafs;
import java.util.Date;
import java.io.*;
import javax.swing.JOptionPane;

public class AttendanceFrame extends javax.swing.JFrame {

    Student s;

    public AttendanceFrame() {
        try {
            FileInputStream f1 = new FileInputStream("data/student.ser");
            ObjectInputStream o1 = new ObjectInputStream(f1);
            s = (Student) o1.readObject();
            o1.close();
            f1.close();


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Some Error occured, please try registering again");
        }

        initComponents();
        
        switch (s.subjectNumber) {
            default:
                break;
            case (1):
                this.remove(labelSubject2);
                this.remove(txtAttendance2);
            case (2):
                this.remove(labelSubject3);
                this.remove(txtAttendance3);
            case (3):
                this.remove(labelSubject4);
                this.remove(txtAttendance4);
            case (4):
                this.remove(labelSubject5);
                this.remove(txtAttendance5);
            case (5):
                this.remove(labelSubject6);
                this.remove(txtAttendance6);
        }
        
        for(int i=0; i<s.subjectNumber; i++)
            s.subject[i].calculateAttendance();


        switch (s.subjectNumber) {
            case (6):
                labelSubject6.setText(s.subject[5].name);
                txtAttendance6.setText("" + s.subject[5].attendance+"%");
            case (5):
                labelSubject5.setText(s.subject[4].name);
                txtAttendance5.setText("" + s.subject[4].attendance+"%");
            case (4):
                labelSubject4.setText(s.subject[3].name);
                txtAttendance4.setText("" + s.subject[3].attendance+"%");
            case (3):
                labelSubject3.setText(s.subject[2].name);
                txtAttendance3.setText("" + s.subject[2].attendance+"%");
            case (2):
                labelSubject2.setText(s.subject[1].name);
                txtAttendance2.setText("" + s.subject[1].attendance+"%");
            case (1):
                labelSubject1.setText(s.subject[0].name);
                txtAttendance1.setText("" + s.subject[0].attendance+"%");
            default:
                break;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSubject1 = new javax.swing.JLabel();
        txtAttendance1 = new javax.swing.JTextField();
        labelSubject2 = new javax.swing.JLabel();
        txtAttendance2 = new javax.swing.JTextField();
        labelSubject3 = new javax.swing.JLabel();
        txtAttendance3 = new javax.swing.JTextField();
        labelSubject4 = new javax.swing.JLabel();
        txtAttendance4 = new javax.swing.JTextField();
        labelSubject5 = new javax.swing.JLabel();
        txtAttendance5 = new javax.swing.JTextField();
        labelSubject6 = new javax.swing.JLabel();
        txtAttendance6 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnDetails = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(680, 480));
        getContentPane().setLayout(new java.awt.GridLayout(0, 2));

        labelSubject1.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject1.setText("jLabel1");
        getContentPane().add(labelSubject1);

        txtAttendance1.setEditable(false);
        txtAttendance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttendance1ActionPerformed(evt);
            }
        });
        getContentPane().add(txtAttendance1);

        labelSubject2.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject2.setText("jLabel2");
        getContentPane().add(labelSubject2);

        txtAttendance2.setEditable(false);
        getContentPane().add(txtAttendance2);

        labelSubject3.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject3.setText("jLabel3");
        getContentPane().add(labelSubject3);

        txtAttendance3.setEditable(false);
        txtAttendance3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAttendance3ActionPerformed(evt);
            }
        });
        getContentPane().add(txtAttendance3);

        labelSubject4.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject4.setText("jLabel4");
        getContentPane().add(labelSubject4);

        txtAttendance4.setEditable(false);
        getContentPane().add(txtAttendance4);

        labelSubject5.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject5.setText("jLabel1");
        getContentPane().add(labelSubject5);

        txtAttendance5.setEditable(false);
        getContentPane().add(txtAttendance5);

        labelSubject6.setFont(new java.awt.Font("Ubuntu", 1, 24)); // NOI18N
        labelSubject6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubject6.setText("jLabel2");
        getContentPane().add(labelSubject6);

        txtAttendance6.setEditable(false);
        getContentPane().add(txtAttendance6);

        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);

        btnDetails.setText("Check Details");
        btnDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetailsActionPerformed(evt);
            }
        });
        getContentPane().add(btnDetails);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAttendance3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttendance3ActionPerformed

    }//GEN-LAST:event_txtAttendance3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new DAFS().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtAttendance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAttendance1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAttendance1ActionPerformed

    private void btnDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetailsActionPerformed
        new Details().setVisible(true);
    }//GEN-LAST:event_btnDetailsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AttendanceFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AttendanceFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetails;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel labelSubject1;
    private javax.swing.JLabel labelSubject2;
    private javax.swing.JLabel labelSubject3;
    private javax.swing.JLabel labelSubject4;
    private javax.swing.JLabel labelSubject5;
    private javax.swing.JLabel labelSubject6;
    private javax.swing.JTextField txtAttendance1;
    private javax.swing.JTextField txtAttendance2;
    private javax.swing.JTextField txtAttendance3;
    private javax.swing.JTextField txtAttendance4;
    private javax.swing.JTextField txtAttendance5;
    private javax.swing.JTextField txtAttendance6;
    // End of variables declaration//GEN-END:variables
}
