package dafs;
import java.io.*;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
public class DAFS extends javax.swing.JFrame {

    /**
     * Creates new form DAFS
     */
    Student s;
    static boolean isRegisterFlag;
    public DAFS() {
        initComponents();
        try
        {
            FileInputStream fIN = new FileInputStream("data/student.ser");
            ObjectInputStream objFile = new ObjectInputStream(fIN);
            s = (Student)objFile.readObject();
            isRegisterFlag = true;
        }
        catch(FileNotFoundException f)
        {
            new OpeningFrame().setVisible(true);
            isRegisterFlag = false;
        }
        catch(Exception ioe)
        {}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        btnAttend = new javax.swing.JButton();
        btnBudget = new javax.swing.JButton();
        btnHangman = new javax.swing.JButton();
        btnMedia = new javax.swing.JButton();
        btnEvent = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setLayout(new java.awt.GridLayout(0, 1));

        jPanel3.setLayout(new java.awt.GridLayout(0, 1));

        jPanel4.setLayout(new java.awt.GridLayout(5, 1));

        btnAttend.setText("Check Attendance");
        btnAttend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttendActionPerformed(evt);
            }
        });
        jPanel4.add(btnAttend);

        btnBudget.setText("Check Budget");
        btnBudget.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBudgetActionPerformed(evt);
            }
        });
        jPanel4.add(btnBudget);

        btnHangman.setText("Hangman");
        btnHangman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHangmanActionPerformed(evt);
            }
        });
        jPanel4.add(btnHangman);

        btnMedia.setText("Media Integration");
        btnMedia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMediaActionPerformed(evt);
            }
        });
        jPanel4.add(btnMedia);

        btnEvent.setText("Event Reminder");
        btnEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEventActionPerformed(evt);
            }
        });
        jPanel4.add(btnEvent);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 663, Short.MAX_VALUE)
                .addGap(4, 4, 4))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttendActionPerformed
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel label = new javax.swing.JLabel("Enter your pin");
        javax.swing.JPasswordField pass = new javax.swing.JPasswordField(4);
        
        panel.add(label);
        panel.add(pass);
        
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Verification", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
 
        if(option==0)
        {
            char[] password = pass.getPassword();
            
            if(new String(password).equals(s.password))
            {
                new AttendanceFrame().setVisible(true);
                dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid Pin");
        }
    }//GEN-LAST:event_btnAttendActionPerformed

    private void btnHangmanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHangmanActionPerformed
        Thread t = new Thread(new hangman.Hangman());
        t.run();
        dispose();
    }//GEN-LAST:event_btnHangmanActionPerformed

    private void btnBudgetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBudgetActionPerformed
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel label = new javax.swing.JLabel("Enter your pin");
        javax.swing.JPasswordField pass = new javax.swing.JPasswordField(4);
        
        panel.add(label);
        panel.add(pass);
        
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Verification", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
 
        if(option==0)
        {
            char[] password = pass.getPassword();
            
            if(new String(password).equals(s.password))
            {
                new BudgetFrame().setVisible(true);
                dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid Pin");
        }
                                            
    }//GEN-LAST:event_btnBudgetActionPerformed

    private void btnEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEventActionPerformed
        javax.swing.JPanel panel = new javax.swing.JPanel();
        javax.swing.JLabel label = new javax.swing.JLabel("Enter your pin");
        javax.swing.JPasswordField pass = new javax.swing.JPasswordField(4);
        
        panel.add(label);
        panel.add(pass);
        
        String[] options = new String[]{"OK", "Cancel"};
        int option = JOptionPane.showOptionDialog(null, panel, "Verification", JOptionPane.NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
 
        if(option==0)
        {
            char[] password = pass.getPassword();
            
            if(new String(password).equals(s.password))
            {
                new EventReminderFrame().setVisible(true);
                dispose();
            }
            else
                JOptionPane.showMessageDialog(null, "Invalid Pin");
        }
          
    }//GEN-LAST:event_btnEventActionPerformed

    private void btnMediaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMediaActionPerformed
        new StartMediaPlayer().run();
    }//GEN-LAST:event_btnMediaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DAFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DAFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DAFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DAFS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DAFS dafs = new DAFS();
                dafs.setVisible(true);
                if(isRegisterFlag==false)
                        dafs.dispose();

                Calendar cal = Calendar.getInstance();
                int currentHour = cal.get(Calendar.HOUR);
                int currentMinute = cal.get(Calendar.MINUTE);
                
          
                if(currentHour==10&&currentMinute==13)
                {
                    new Notification().setVisible(true);
                    
                    Date temp = new Date();
                     
                    for (int i = 0; i < dafs.s.eventCount; i++) 
                        if (dafs.s.event[i].date.getDate() == temp.getDate()
                                && dafs.s.event[i].date.getMonth() == temp.getMonth()
                                && dafs.s.event[i].date.getYear() == temp.getYear()) {
                            JOptionPane.showMessageDialog(null, dafs.s.event[i].name);                                                       
                        }
                        
                if(dafs.s.budget.budgetRemaining<dafs.s.budget.crucialPoint)
                        JOptionPane.showMessageDialog(null, "Warning, you have very less money left");
                
         
                }
               
            }
        });
    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAttend;
    private javax.swing.JButton btnBudget;
    private javax.swing.JButton btnEvent;
    private javax.swing.JButton btnHangman;
    private javax.swing.JButton btnMedia;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
