package dafs;
import java.io.*;
import javax.swing.JOptionPane;
import javax.swing.JComboBox;
import javax.swing.table.*;
import javax.swing.JTable;
import javax.swing.DefaultCellEditor; 
import java.util.Date;

public class SetUpAccount3 extends javax.swing.JFrame {

    Student s;
    Timetable tt;
    public SetUpAccount3() {
        try
        {
            FileInputStream f = new FileInputStream("data/student.ser");
            ObjectInputStream obj = new ObjectInputStream(f);
            s = (Student) obj.readObject();
            f.close(); obj.close();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, "Error");}
        initComponents();
        DefaultTableModel model = (DefaultTableModel)timetable.getModel();
            for(int i=0; i<s.lectureNumber; i++)
                model.addRow(new Object[]{"","","","","",""});
 
        JOptionPane.showMessageDialog(null, "Please enter all your subjects \nbefore we continue");
        
        for(int i=1; i<=s.subjectNumber; i++)
            s.subject[i-1].name = JOptionPane.showInputDialog("Enter subject " + i);
        
        JOptionPane.showMessageDialog(null, "Please enter total number of lectures \nyou have in the course for each subject");
  
        for(int i=1; i<=s.subjectNumber; i++)
            s.subject[i-1].totalLectures = Integer.parseInt(JOptionPane.showInputDialog(s.subject[i-1].name));
        
        JOptionPane.showMessageDialog(null, "Please enter total number of lectures \nyou have attended for each subject");
  
        for(int i=1; i<=s.subjectNumber; i++)
            s.subject[i-1].lecturesAttended = Integer.parseInt(JOptionPane.showInputDialog(s.subject[i-1].name));
        
         JOptionPane.showMessageDialog(null, "Please enter total number of lectures \nthat have took place for each subject till today");
  
        for(int i=1; i<=s.subjectNumber; i++)
            s.subject[i-1].totalLecturesTillDate = Integer.parseInt(JOptionPane.showInputDialog(s.subject[i-1].name));
           
        
        TableColumn Monday = timetable.getColumnModel().getColumn(0);
        TableColumn Tuesday = timetable.getColumnModel().getColumn(1);
        TableColumn Wednesday = timetable.getColumnModel().getColumn(2);
        TableColumn Thursday = timetable.getColumnModel().getColumn(3);
        TableColumn Friday = timetable.getColumnModel().getColumn(4);
        TableColumn Saturday = timetable.getColumnModel().getColumn(5);
        
        JComboBox comboBox = new JComboBox();
        for(int i=0; i<s.subjectNumber; i++)
            comboBox.addItem(s.subject[i].name);
        
        Monday.setCellEditor(new DefaultCellEditor(comboBox));
        Tuesday.setCellEditor(new DefaultCellEditor(comboBox));
        Wednesday.setCellEditor(new DefaultCellEditor(comboBox));
        Thursday.setCellEditor(new DefaultCellEditor(comboBox));
        Friday.setCellEditor(new DefaultCellEditor(comboBox));
        Saturday.setCellEditor(new DefaultCellEditor(comboBox));

        tt = new Timetable(s.lectureNumber);
    }
    public static String[][] getTableData (JTable table) {
    DefaultTableModel dtm = (DefaultTableModel) table.getModel();
    int nRow = dtm.getRowCount(), nCol = dtm.getColumnCount();
    String[][] tableData = new String[nRow][nCol];
    for (int i = 0 ; i < nRow ; i++)
        for (int j = 0 ; j < nCol ; j++)
            tableData[i][j] = dtm.getValueAt(i,j).toString();
    return tableData;
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        timetable = new javax.swing.JTable();
        btnFinish = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Set Up your Time Table");

        timetable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday"
            }
        ));
        jScrollPane1.setViewportView(timetable);

        btnFinish.setText("FINISH");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 477, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(btnFinish, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnFinish, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        String table[][] = new String[s.lectureNumber][6];
        table = getTableData(timetable);
        for(int i=0; i<s.lectureNumber; i++)
            tt.Monday[i] = table[i][0];
        for(int i=0; i<s.lectureNumber; i++)
            tt.Tuesday[i] = table[i][1];
        for(int i=0; i<s.lectureNumber; i++)
            tt.Wednesday[i] = table[i][2];
        for(int i=0; i<s.lectureNumber; i++)
            tt.Thursday[i] = table[i][3];
        for(int i=0; i<s.lectureNumber; i++)
            tt.Friday[i] = table[i][4];
        for(int i=0; i<s.lectureNumber; i++)
            tt.Saturday[i] = table[i][5];
        
        try
        {
            FileOutputStream fout = new FileOutputStream("data/student.ser");
            ObjectOutputStream oout = new ObjectOutputStream(fout);
            oout.writeObject(s);
            oout.close(); fout.close();
            
            FileOutputStream f2 = new FileOutputStream("data/timetable.ser");
            ObjectOutputStream o2 = new ObjectOutputStream(f2);
            o2.writeObject(tt);
            o2.close(); f2.close();
            
            new DAFS().setVisible(true);
            dispose();
        }
        catch(Exception e)
        {JOptionPane.showMessageDialog(null, "An error occured please try again later");}
    }//GEN-LAST:event_btnFinishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetUpAccount3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetUpAccount3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetUpAccount3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetUpAccount3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetUpAccount3().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable timetable;
    // End of variables declaration//GEN-END:variables
}
